version: '3'
services:
  nginx:
      image: nginx:alpine
      restart: always
      hostname: nginx
      ports:
        - "80:80"
      volumes:
        - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro

  nginx_ssl:
      image: nginx:alpine
      restart: always
      hostname: nginx_ssl
      ports:
        - "443:443"
      volumes:
        - ./conf/nginx_ssl.conf:/etc/nginx/nginx.conf:ro
        - ./conf/ssl:/etc/selfsigned
  mariadb: 
    restart: always
    image: mariadb
    hostname: mariadb
    volumes: 
      - ./data/mysql:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: changepasswd


  semaphore:
      restart: always
      image: prangm/ansible-semaphore
      hostname: semaphore
      volumes:
        - ./conf/semaphore/:/semaphore
      links:
        - mariadb
        - nginx
        - nginx_ssl
      depends_on:
        - mariadb
      environment:
        - WAIT_HOSTS=mariadb:3306
        - WAIT_HOSTS_TIMEOUT=300
        - WAIT_SLEEP_INTERVAL=30
        - WAIT_HOST_CONNECT_TIMEOUT=30
        - MYSQL_ROOT_PASSWORD=changepasswd
      command: ["-c", "/wait && /update_conf && semaphore -migrate -config /semaphore/config.json && /add_admin ; semaphore -config /semaphore/config.json" ]

    
